language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "0.10"
  - "4.0"
  - "4.1"
  - "4.4"
  - "5.11"
  - "6.0"
  - "6.1"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
